# Generated by Django 5.2.11 on 2026-03-02 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the holiday (e.g., Republic Day)', max_length=200)),
                ('date', models.DateField(help_text='Date of the holiday')),
                ('holiday_type', models.CharField(choices=[('GOVT', 'Government Holiday'), ('FESTIVAL', 'Festival Holiday'), ('OPTIONAL', 'Optional Holiday'), ('COMPANY', 'Company Event')], default='GOVT', max_length=20)),
                ('year', models.IntegerField(help_text='Year for easy filtering')),
                ('description', models.TextField(blank=True, help_text='Additional details about the holiday', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is active')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='True if created by system automatically')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created/modified this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HolidayNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_count', models.IntegerField(default=0, help_text='Number of employees notified')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hrms.holiday')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['year', 'date'], name='hrms_holida_year_7574fb_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['holiday_type'], name='hrms_holida_holiday_b79925_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
    ]
