# Generated by Django 5.2.12 on 2026-03-12 06:16
# Generated by Django 5.2.11 on 2026-03-07 15:22

# Generated by Django 5.2.11 on 2026-03-07 15:22


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
