# Generated by Django 5.2.12 on 2026-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_leave_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='TEMP001', max_length=50),
            preserve_default=False,
        ),
    ]
