# Generated by Django 5.2.11 on 2026-03-02 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_holiday_holidaynotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the meeting/event', max_length=200)),
                ('date', models.DateField(help_text='Date of the meeting')),
                ('time', models.TimeField(blank=True, help_text='Time of the meeting (optional)', null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=1, help_text='Duration in hours (e.g., 1.5 for 1.5 hours)', max_digits=3, null=True)),
                ('location', models.CharField(blank=True, help_text='Location/Venue of the meeting', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Meeting agenda or description')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Current status of the meeting', max_length=20)),
                ('is_holiday', models.BooleanField(default=False, help_text='Auto-set if date is a holiday')),
                ('holiday_warning', models.CharField(blank=True, help_text='Warning if scheduled on holiday', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, help_text='Employees attending this meeting', related_name='meetings', to='hrms.employee')),
                ('created_by', models.ForeignKey(help_text='User who created this meeting', on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
