# Generated by Django 6.0.2 on 2026-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcement_files/'),
        ),
    ]
