# Generated by Django 5.2.11 on 2026-03-03 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_meeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidaynotification',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Holiday Notification', 'verbose_name_plural': 'Holiday Notifications'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='event_duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duration in hours (e.g., 2.5 for 2.5 hours)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='event_location',
            field=models.CharField(blank=True, help_text='Where the event will take place', max_length=200),
        ),
        migrations.AddField(
            model_name='holiday',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Time of the event (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='note',
            field=models.TextField(blank=True, help_text='Additional details about the event (e.g., venue, time, instructions)', null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='registration_deadline',
            field=models.DateField(blank=True, help_text='Last date to register for the event', null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='requires_registration',
            field=models.BooleanField(default=False, help_text='Do employees need to register for this event?'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='target_department',
            field=models.CharField(blank=True, help_text="Department name if visibility is 'DEPARTMENT'", max_length=100),
        ),
        migrations.AddField(
            model_name='holiday',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'All Employees'), ('DEPARTMENT', 'Specific Department'), ('SELECTED', 'Selected Employees')], default='ALL', help_text='Who can see this event?', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('GOVT', 'Government Holiday'), ('FESTIVAL', 'Festival Holiday'), ('OPTIONAL', 'Optional Holiday'), ('COMPANY', 'Company Event'), ('MEETING', 'Meeting'), ('TRAINING', 'Training'), ('PARTY', 'Celebration')], default='GOVT', max_length=20),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='holiday',
            field=models.ForeignKey(help_text='The holiday this notification is for', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hrms.holiday'),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the notification was sent'),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='Who sent the notification (null if system sent)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
