# Generated by Django 6.0.3 on 2026-03-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_employee_employee_id'),
        ('hrms', '0005_remove_employee_full_name_employee_education_and_more'),
    ]

    operations = [
    ]
