# Generated by Django 6.0.3 on 2026-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_merge_20260313_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
