# Generated by Django 6.0.3 on 2026-03-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_user_has_set_password_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
