# Generated by Django 5.2.12 on 2026-03-16 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('history', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='casual_leave_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='casual_leave_total',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid_leave_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='paid_leave_total',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_total',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
