# Generated by Django 5.2.11 on 2026-03-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_alter_leave_employee'),
        ('hrms', '0009_department_employee_casual_leave_balance_and_more'),
    ]

    operations = [
    ]
