# Generated by Django 5.2.11 on 2026-03-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_employee_employee_id_alter_leave_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='holidaynotification',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveIndex(
            model_name='holiday',
            name='hrms_holida_year_7574fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='holiday',
            name='hrms_holida_holiday_b79925_idx',
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='holidaynotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holidaynotification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='holidaynotification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='event_duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='event_location',
            field=models.CharField(blank=True, help_text='Location of holiday event', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Time of any holiday event', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('NATIONAL', 'National Holiday'), ('RELIGIOUS', 'Religious Holiday'), ('COMPANY', 'Company Holiday'), ('OTHER', 'Other')], default='NATIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='note',
            field=models.TextField(blank=True, help_text='Special instructions or notes for employees', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='requires_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hrms.holiday'),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='recipient_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in hours', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='holiday_warning',
            field=models.BooleanField(default=False, help_text='Warning if meeting is near a holiday'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Auto-set if meeting falls on a holiday'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='target_department',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='visibility',
        ),
    ]
