# Generated by Django 5.2.12 on 2026-03-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_salary'),
        ('hrms', '0012_delete_department_employee_emergency_contact_name_and_more'),
    ]

    operations = [
    ]
