# Generated by Django 5.2.12 on 2026-03-30 11:48

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_leave_approved_by_leave_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=models.SET_NULL, related_name='managed_department_obj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
        ),
    ]
