# Generated by Django 5.2.11 on 2026-04-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_announcement_attachment'),
        ('hrms', '0012_alter_holiday_options_and_more'),
        ('hrms', '0015_recreate_department_table'),
    ]

    operations = [
    ]
