# Generated by Django 5.2.11 on 2026-04-07 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_merge_20260402_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date'], 'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='attachment',
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date')},
        ),
        migrations.RemoveField(
            model_name='holidaynotification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='holidaynotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='holidaynotification',
            name='read_at',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created/modified this holiday', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(help_text='Date of the holiday'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the holiday', null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('GOVT', 'Government Holiday'), ('FESTIVAL', 'Festival Holiday'), ('OPTIONAL', 'Optional Holiday'), ('COMPANY', 'Company Event')], default='GOVT', help_text='Type of holiday', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this holiday is active'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='True if created by system automatically'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(help_text='Name of the holiday (e.g., Republic Day)', max_length=200),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(help_text='Year for easy filtering'),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='recipient_count',
            field=models.IntegerField(default=0, help_text='Number of employees notified'),
        ),
        migrations.AlterField(
            model_name='holidaynotification',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Employees attending this meeting', related_name='meetings', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this meeting', on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(help_text='Date of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, help_text='Meeting agenda or description'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duration in hours (e.g., 1.5)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='holiday_warning',
            field=models.CharField(blank=True, help_text='Warning if scheduled on holiday', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_holiday',
            field=models.BooleanField(default=False, help_text='Auto-set if date is a holiday'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, help_text='Location/Venue of the meeting', max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', help_text='Current status of the meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of the meeting (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(help_text='Title of the meeting/event', max_length=200),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='note',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='requires_registration',
        ),
    ]
