# Generated by Django 5.2.11 on 2026-04-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_alter_holiday_options_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('PAID', 'Paid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('MARRIAGE', 'Marriage Leave')], max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown to users', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_days', models.DecimalField(decimal_places=1, default=0, help_text='Default leave days per year/occurrence', max_digits=5)),
                ('max_days_per_request', models.DecimalField(decimal_places=1, default=30, max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='Yearly recurring or one-time')),
                ('is_active', models.BooleanField(default=True)),
                ('gender_restriction', models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male Only'), ('FEMALE', 'Female Only')], default='ALL', max_length=10)),
                ('min_service_days', models.IntegerField(default=0, help_text='Minimum days of service required')),
                ('max_children', models.IntegerField(default=0, help_text='For maternity: max children covered')),
                ('requires_document', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcement_files/'),
        ),
        migrations.AddField(
            model_name='leave',
            name='child_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='child_number',
            field=models.IntegerField(blank=True, help_text='1st, 2nd, 3rd child', null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_adoption',
            field=models.BooleanField(default=False, help_text='For adoption cases'),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_first_marriage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_surrogacy',
            field=models.BooleanField(default=False, help_text='For surrogacy cases'),
        ),
        migrations.AddField(
            model_name='leave',
            name='marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='marriage_proofs/'),
        ),
        migrations.AddField(
            model_name='leave',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('PAID', 'Paid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('MARRIAGE', 'Marriage Leave')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('PAID', 'Paid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('MARRIAGE', 'Marriage Leave')], max_length=20)),
                ('total_allocated', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_used', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('remaining', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('year', models.IntegerField()),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('carry_forward_days', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hrms.employee')),
            ],
            options={
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
