# Generated by Django 5.2.11 on 2026-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_add_leave_special_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Team Lead', 'Team Lead'), ('HR Executive', 'HR Executive'), ('HR Associate', 'HR Associate'), ('Accountant', 'Accountant'), ('Sales Executive', 'Sales Executive'), ('Marketing Executive', 'Marketing Executive'), ('UI/UX Designer', 'UI/UX Designer'), ('QA Tester', 'QA Tester'), ('DevOps Engineer', 'DevOps Engineer'), ('Support Engineer', 'Support Engineer'), ('Intern', 'Intern')], default='Intern', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
