# Generated by Django 5.2.11 on 2026-04-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_alter_employee_department_alter_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='previous_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
