# Generated by Django 5.2.11 on 2026-04-23 06:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_employee_previous_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentVisitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, unique=True)),
                ('total_visits', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('avg_duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='previous_designation',
            new_name='account_holder_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('SALARY', 'Salary')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='institute_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marks_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('cgpa', 'CGPA'), ('gpa', 'GPA'), ('grade', 'Grade')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marks_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_of_passing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('visitor_type', models.CharField(choices=[('GUEST', 'Guest'), ('VENDOR', 'Vendor'), ('INTERN', 'Intern'), ('CANDIDATE', 'Interview Candidate')], default='GUEST', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_visiting', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('id_proof_type', models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DRIVING', 'Driving License'), ('PASSPORT', 'Passport'), ('VOTER', 'Voter ID'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('id_proof_number', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('current_semester', models.IntegerField(blank=True, null=True)),
                ('mentor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL)),
                ('intern', models.ForeignKey(limit_choices_to={'visitor_type': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hrms.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='InternDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('current_semester', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('internship_duration_months', models.IntegerField(default=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('marks_details', models.JSONField(blank=True, default=dict)),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='intern_offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interns', to=settings.AUTH_USER_MODEL)),
                ('intern', models.OneToOneField(limit_choices_to={'visitor_type': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='intern_details', to='hrms.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='GuestVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('MEETING', 'Business Meeting'), ('INTERVIEW', 'Interview'), ('DELIVERY', 'Delivery'), ('SERVICE', 'Service/Maintenance'), ('TRAINING', 'Training'), ('EVENT', 'Event'), ('OTHER', 'Other')], default='MEETING', max_length=50)),
                ('purpose_other', models.CharField(blank=True, max_length=200, null=True)),
                ('host_name', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_room', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_check_in', models.DateTimeField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('entry_gate', models.CharField(choices=[('MAIN', 'Main Gate'), ('EAST', 'East Gate'), ('WEST', 'West Gate'), ('NORTH', 'North Gate'), ('SOUTH', 'South Gate'), ('SERVICE', 'Service Gate')], default='MAIN', max_length=20)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('CHECKED_IN', 'Checked-in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='EXPECTED', max_length=20)),
                ('badge_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visits', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hrms.visitor')),
            ],
            options={
                'ordering': ['-expected_check_in'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('CHECK_IN', 'Checked In'), ('CHECK_OUT', 'Checked Out'), ('CANCEL', 'Cancelled'), ('DELETE', 'Deleted')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('guest_visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hrms.guestvisit')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hrms.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='InternAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'On Leave')], default='PRESENT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('intern', models.ForeignKey(limit_choices_to={'visitor_type': 'INTERN'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrms.visitor')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('intern', 'date')},
            },
        ),
    ]
