# Generated by Django 5.2.11 on 2026-04-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_departmentvisitstats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guestvisit',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guestvisit',
            name='expected_check_in',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='guestvisit',
            name='status',
            field=models.CharField(choices=[('EXPECTED', 'Expected'), ('CHECKED_IN', 'Checked-in'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='EXPECTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this holiday is active'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Year for easy filtering'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('CASUAL', 'Casual Leave'), ('PAID', 'Paid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('MARRIAGE', 'Marriage Leave')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('VENDOR', 'Vendor'), ('INTERN', 'Intern'), ('CANDIDATE', 'Interview Candidate')], db_index=True, default='GUEST', max_length=20),
        ),
    ]
